### ISSUE TITLE
alignment of "enter your phone number"

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/call-congress-net-neutrality#10]
![phonealign](https://cloud.githubusercontent.com/assets/197334/6071727/26ec5628-ad67-11e4-859e-1231cc40d20d.png)

The distance from the input to the left of the phone icon should be the same as the distance from the end of the phone input to the "r" at the end of "Enter your phone number"

**Comment by cassiemc** [comment]
:exclamation: :ok_hand:

**Comment by alicoding** [comment]
I have done a lot of fix for QA and I think it will mess this up once we land other PR. so I will wait and fix this one after.
