### ISSUE TITLE
Improve phone number input

### ISSUE THREAD

**Issue by simonwex** [mozilla/call-congress-net-neutrality#2]
Possibly use something like this, limiting to US numbers:
https://github.com/Bluefieldscom/intl-tel-input

**Comment by ScottDowne** [comment]
I think we need to get a designer to chime in on these plugins.

**Comment by ScottDowne** [comment]
I'm actually not a fan of this vs a simple accept everything and change nothing.

**Comment by alicoding** [comment]
IMO I think we need to create that standard for what our input accept and make it obvious to the user what we are expecting. If we simply accept everything and then we process that I think there are higher chance of going back and forth with the user to ask for their input again and again. If we do display what we are expecting which in our case is very obvious that we want their phone number and it is really obvious to me and I'm sure to them as well that what they need to input when they see the placeholder.

**Comment by davidascher** [comment]
A specific q that the original form left unspecified to me as a user is
whether I was supposed to type the ()'s and the - that are in the sample.
Different forms behave differently.

**Comment by valianttry** [comment]
there are also an incorrect # of digits for a US call:
![mozilla_firefox](https://cloud.githubusercontent.com/assets/9830371/6072844/62f4c92c-ad5b-11e4-9e7e-29d8be53f722.png)

**Comment by alicoding** [comment]
@valianttry Thanks I've fixed that!

**Comment by simonwex** [comment]
Let's call this closed. Handling has been much improved. :cake:

**Comment by davidascher** [comment]
Nice.
