### ISSUE TITLE
Got "we have encountered an error - goodbye"

### ISSUE THREAD

**Issue by valianttry** [mozilla/call-congress-net-neutrality#22]
I was connected to an FCC commissioner, but the voicemail said "this mailbox is full" then the system voice for (Twilio?) said "Sorry we've encountered an error" and then it hung up.

**Comment by valianttry** [comment]
This happened again today. I got Feinstein's office but it said i'd have to wait 15 minutes on hold, so i pressed "star" to move to the next call and got "we're sorry, an application error has occurred, goodbye" + hangup.

**Comment by jdotpz** [comment]
This is now resolved.  We should verify, but it is fixed.
