### ISSUE TITLE
while calling, the call script bubble colour is off

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/call-congress-net-neutrality#26]
It looks as if the call script bubble is still from the preview page light blue and not dark blue as it should be

**Comment by alicoding** [comment]
I'm seeing this 
![screenshot 2015-02-05 22 21 54](https://cloud.githubusercontent.com/assets/4368149/6074107/8f51ae34-ad85-11e4-9a79-633915654ec1.png)

**Comment by ScottDowne** [comment]
Yeah, turns out I was setting classes to change state instead of actually calling.

This isn't enough anymore.
