### ISSUE TITLE
Add Countdown box's shadow

### ISSUE THREAD

**Issue by cassiemc** [mozilla/call-congress-net-neutrality#38]
There should be a slight shadow underneath the countdown box. Not sure if you can recreate that with css, so here's the asset (you may not need the 2x asset for this, but it's there if you do): https://www.dropbox.com/sh/vmeqdd5ibfqndy8/AAA24u-zmfaFId7O7Nbz3aJSa?dl=0

![counter-shadow](https://cloud.githubusercontent.com/assets/1186326/6081920/109a166a-adeb-11e4-9b99-97ff275801ba.png)

**Comment by simonwex** [comment]
Hey @cassiemc, I was able to do this just with CSS, does it pass muster?

![image](https://cloud.githubusercontent.com/assets/25260/6089443/8f6ebb7c-ae17-11e4-89db-b6ee95664690.png)

**Comment by simonwex** [comment]
@cassiemc, I had @flukeout look at it, he was happy enough, re-open if you'd like some tweaks.

**Comment by cassiemc** [comment]
does the trick, thanks @simonwex!
