### ISSUE TITLE
When clicking defocusing phone number input a javascript error occurs if input is blank

### ISSUE THREAD

**Issue by simonwex** [mozilla/call-congress-net-neutrality#5]
![image](https://cloud.githubusercontent.com/assets/25260/6071337/aa34cd26-ad49-11e4-864a-fb684af89169.png)

**Comment by alicoding** [comment]
Does it work for you here? http://alicoding.github.io/call-congress-net-neutrality/ @simonwex  I've tested and it's working both in Firefox and Chrome with Private mode as well.

**Comment by flukeout** [comment]
Happens to me when I focus the input field, add nothing, then hit 'tab' to defocus the field. In chrome.

**Comment by simonwex** [comment]
Ah, good catch @flukeout it's the defocusing of the input field.

**Comment by alicoding** [comment]
Ah I can see that now too!

**Comment by simonwex** [comment]
^ Updated title

**Comment by alicoding** [comment]
Hmm... Apparently it will error when press tab or shift+tab (next or previous field). I wonder if this is because of the jquery-mask plugin, but it doesn't break anything here (Thanks god!).

**Comment by flukeout** [comment]
A couple of points:
* The magic formatting breaks things when you add a non-number character in the middle of the phone number (like might happen when you're editing a bad number) - it erases everything after the bad character
* I'm unable to Command+A (select all) to select the phone number after I've added it unless I do it very slowly
* Should we auto-focus the input field on desktop?

**Comment by alicoding** [comment]
@simonwex https://github.com/mozilla/call-congress-net-neutrality/pull/7 so we don't need those at all \o/

**Comment by alicoding** [comment]
@flukeout I've fixed this

- [x] fixed the non number break format

**Comment by alicoding** [comment]
The `Command-A` (Select all) is not doable with this plugin, but there is another one except the file size for that plugin is huge (50kb vs 5kb)

This one is better but too big https://github.com/RobinHerbots/jquery.inputmask
This one is the one we are using right now http://igorescobar.github.io/jQuery-Mask-Plugin/

I've fixed the text cursor.

**Comment by alicoding** [comment]
Now only two things we can't fix until we can come up with our own quick `mask` js hack or choose different plugin here @flukeout @simonwex for Select all I mean.
