### ISSUE TITLE
Phone number editing adds strange behavious

### ISSUE THREAD

**Issue by simonwex** [mozilla/call-congress-net-neutrality#6]
* When editing phone number input, if `(` is edited, it's added back in. 
* If a new number is added at the beginning of the phone number, all other digits are replaced
  1. enter a few digits
  2. miss the first number of an area code
  3. hit home key
  4. enter number
  5. all other numbers are removed.
* Handling of letters is a bit awkward

![image](https://cloud.githubusercontent.com/assets/25260/6071407/6b82f7a0-ad4a-11e4-8f82-4b537acbd6ef.png)

**Comment by simonwex** [comment]
I'd say this is a low-priority, but might be made better by using the plugin mentioned in #2

**Comment by alicoding** [comment]
@simonwex fixed in here https://github.com/mozilla/call-congress-net-neutrality/pull/7
